### ISSUE TITLE
[Insight] Unused use statement should be avoided - in src/DeForm.php, line 5

### ISSUE THREAD

**Issue by radmen** [DeSmart/deform#5]
**[in src/DeForm.php, line 5](https://github.com/DeSmart/deform/blob/3a62214c8e1366155e5c532d70fced530f8ce1b5/src/DeForm.php#L5)**

> The class `DeForm\Validation\ValidatorInterface` is declared but never used. You should remove the `use` statement.

``` php
<?php namespace DeForm;

use DeForm\Node\NodeInterface;
use DeForm\Element\ElementInterface;
use DeForm\Validation\ValidatorInterface;
use DeForm\Request\RequestInterface as Request;
use DeForm\Validation\ValidatorFactoryInterface;
use DeForm\Document\DocumentInterface as Document;

class DeForm
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/85fedba2-9085-4052-8e7a-d9b9692f08c6/analyses/1)_

**Comment by pomek** [comment]
Fixed in 1f452808f148a97699145ea0e17b82f760460502
