### ISSUE TITLE
[Insight] Source code should not contain TODO comments - in src/Factory/ElementFactory.php, line 37

### ISSUE THREAD

**Issue by radmen** [DeSmart/deform#6]
**[in src/Factory/ElementFactory.php, line 37](https://github.com/DeSmart/deform/blob/3a62214c8e1366155e5c532d70fced530f8ce1b5/src/Factory/ElementFactory.php#L37)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

``` php
     * Map node type to instance of element.
     *
     * @var array
     */
    protected $mapTypes = [
        // TODO: more inputs
        'input_radio' => 'RadioElement',
        'input_checkbox' => 'CheckboxElement',
        'input_text' => 'TextElement',
        'input_password' => 'TextElement',
        'input_hidden' => 'TextElement',
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/85fedba2-9085-4052-8e7a-d9b9692f08c6/analyses/1)_

**Comment by pomek** [comment]
Fixed in 423f62710c7e6809a88c7d6758b22337a440f1c3
